changing ftx error text
orikalinski/ccxt_lite pull request #32
Opened 2022-06-28 10:20 UTC by yo1122c

relates to ticket https://cornix.atlassian.net/browse/CO-528

Full error text: "Cannot trade futures until you complete the Client Suitability Questionnaire on the website"

2022-07-03 06:23 UTC, giladwa requested changes

2022-07-03 06:23 UTC, giladwa commented on python/ccxt/ftx.py
> +                    'cannot trade futures': PermissionDenied
is it case insensetive?

2022-07-03 06:23 UTC, giladwa commented on python/ccxt/ftx.py
> -                    'you cannot trade futures': PermissionDenied
Make sure to use also here our branch format(same on Jira - same branch names on different repositories).

2022-07-04 09:52 UTC, yo1122c commented
will fix in new PR

2022-07-04 09:52 UTC, closed without merging